config/routes.rb
Rails.application.routes.draw do
  resources :fines
  resources :returns
  resources :borrowers
  resources :users
  resources :books

  root to: 'books#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/borrower.rb
class Borrower < ApplicationRecord
end

app/controllers/borrowers_controller.rb
class BorrowersController < ApplicationController
  before_action :set_borrower, only: [:show, :edit, :update, :destroy]

  # GET /borrowers
  # GET /borrowers.json
  def index
    @borrowers = Borrower.all
  end

  # GET /borrowers/1
  # GET /borrowers/1.json
  def show
  end

  # GET /borrowers/new
  def new
    @borrower = Borrower.new
  end

  # GET /borrowers/1/edit
  def edit
  end

  # POST /borrowers
  # POST /borrowers.json
  def create
    @borrower = Borrower.new(borrower_params)

    respond_to do |format|
      if @borrower.save
        format.html { redirect_to @borrower, notice: 'Borrower was successfully created.' }
        format.json { render :show, status: :created, location: @borrower }
      else
        format.html { render :new }
        format.json { render json: @borrower.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /borrowers/1
  # PATCH/PUT /borrowers/1.json
  def update
    respond_to do |format|
      if @borrower.update(borrower_params)
        format.html { redirect_to @borrower, notice: 'Borrower was successfully updated.' }
        format.json { render :show, status: :ok, location: @borrower }
      else
        format.html { render :edit }
        format.json { render json: @borrower.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /borrowers/1
  # DELETE /borrowers/1.json
  def destroy
    @borrower.destroy
    respond_to do |format|
      format.html { redirect_to borrowers_url, notice: 'Borrower was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_borrower
      @borrower = Borrower.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def borrower_params
      params.require(:borrower).permit(:date_borrower)
    end
end

app/helpers/borrowers_helper.rb
module BorrowersHelper
end

app/views/borrowers/_form.html.erb
<%= form_with(model: borrower, local: true) do |form| %>
  <% if borrower.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(borrower.errors.count, "error") %> prohibited this borrower from being saved:</h2>

      <ul>
      <% borrower.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date_borrower %>
    <%= form.date_select :date_borrower %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/borrowers/edit.html.erb
<h1>Editing Borrower</h1>

<%= render 'form', borrower: @borrower %>

<%= link_to 'Show', @borrower %> |
<%= link_to 'Back', borrowers_path %>

app/views/borrowers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Borrowers</h1>

<table>
  <thead>
    <tr>
      <th>Date borrower</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @borrowers.each do |borrower| %>
      <tr>
        <td><%= borrower.date_borrower %></td>
        <td><%= link_to 'Show', borrower %></td>
        <td><%= link_to 'Edit', edit_borrower_path(borrower) %></td>
        <td><%= link_to 'Destroy', borrower, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Borrower', new_borrower_path %>

app/views/borrowers/new.html.erb
<h1>New Borrower</h1>

<%= render 'form', borrower: @borrower %>

<%= link_to 'Back', borrowers_path %>

app/views/borrowers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date borrower:</strong>
  <%= @borrower.date_borrower %>
</p>

<%= link_to 'Edit', edit_borrower_path(@borrower) %> |
<%= link_to 'Back', borrowers_path %>