config/routes.rb
Rails.application.routes.draw do
  resources :fines
  resources :returns
  resources :borrowers
  resources :users
  resources :books

  root to: 'books#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/fine.rb
class Fine < ApplicationRecord
  belongs_to :returns
end

app/controllers/fines_controller.rb
class FinesController < ApplicationController
  before_action :set_fine, only: [:show, :edit, :update, :destroy]

  # GET /fines
  # GET /fines.json
  def index
    @fines = Fine.all
  end

  # GET /fines/1
  # GET /fines/1.json
  def show
  end

  # GET /fines/new
  def new
    @fine = Fine.new
  end

  # GET /fines/1/edit
  def edit
  end

  # POST /fines
  # POST /fines.json
  def create
    @fine = Fine.new(fine_params)

    respond_to do |format|
      if @fine.save
        format.html { redirect_to @fine, notice: 'Fine was successfully created.' }
        format.json { render :show, status: :created, location: @fine }
      else
        format.html { render :new }
        format.json { render json: @fine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fines/1
  # PATCH/PUT /fines/1.json
  def update
    respond_to do |format|
      if @fine.update(fine_params)
        format.html { redirect_to @fine, notice: 'Fine was successfully updated.' }
        format.json { render :show, status: :ok, location: @fine }
      else
        format.html { render :edit }
        format.json { render json: @fine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fines/1
  # DELETE /fines/1.json
  def destroy
    @fine.destroy
    respond_to do |format|
      format.html { redirect_to fines_url, notice: 'Fine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fine
      @fine = Fine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fine_params
      params.require(:fine).permit(:date_borrower, :returns_id)
    end
end

app/helpers/fines_helper.rb
module FinesHelper
end

app/views/fines/_form.html.erb
<%= form_with(model: fine, local: true) do |form| %>
  <% if fine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fine.errors.count, "error") %> prohibited this fine from being saved:</h2>

      <ul>
      <% fine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date_borrower %>
    <%= form.date_select :date_borrower %>
  </div>

  <div class="field">
    <%= form.label :returns_id %>
    <%= form.text_field :returns_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fines/edit.html.erb
<h1>Editing Fine</h1>

<%= render 'form', fine: @fine %>

<%= link_to 'Show', @fine %> |
<%= link_to 'Back', fines_path %>

app/views/fines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fines</h1>

<table>
  <thead>
    <tr>
      <th>Date borrower</th>
      <th>Returns</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fines.each do |fine| %>
      <tr>
        <td><%= fine.date_borrower %></td>
        <td><%= fine.returns %></td>
        <td><%= link_to 'Show', fine %></td>
        <td><%= link_to 'Edit', edit_fine_path(fine) %></td>
        <td><%= link_to 'Destroy', fine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fine', new_fine_path %>

app/views/fines/new.html.erb
<h1>New Fine</h1>

<%= render 'form', fine: @fine %>

<%= link_to 'Back', fines_path %>

app/views/fines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date borrower:</strong>
  <%= @fine.date_borrower %>
</p>

<p>
  <strong>Returns:</strong>
  <%= @fine.returns %>
</p>

<%= link_to 'Edit', edit_fine_path(@fine) %> |
<%= link_to 'Back', fines_path %>