config/routes.rb
Rails.application.routes.draw do
  resources :fines
  resources :returns
  resources :borrowers
  resources :users
  resources :books

  root to: 'books#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/return.rb
class Return < ApplicationRecord
end

app/controllers/returns_controller.rb
class ReturnsController < ApplicationController
  before_action :set_return, only: [:show, :edit, :update, :destroy]

  # GET /returns
  # GET /returns.json
  def index
    @returns = Return.all
  end

  # GET /returns/1
  # GET /returns/1.json
  def show
  end

  # GET /returns/new
  def new
    @return = Return.new
  end

  # GET /returns/1/edit
  def edit
  end

  # POST /returns
  # POST /returns.json
  def create
    @return = Return.new(return_params)

    respond_to do |format|
      if @return.save
        format.html { redirect_to @return, notice: 'Return was successfully created.' }
        format.json { render :show, status: :created, location: @return }
      else
        format.html { render :new }
        format.json { render json: @return.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /returns/1
  # PATCH/PUT /returns/1.json
  def update
    respond_to do |format|
      if @return.update(return_params)
        format.html { redirect_to @return, notice: 'Return was successfully updated.' }
        format.json { render :show, status: :ok, location: @return }
      else
        format.html { render :edit }
        format.json { render json: @return.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /returns/1
  # DELETE /returns/1.json
  def destroy
    @return.destroy
    respond_to do |format|
      format.html { redirect_to returns_url, notice: 'Return was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_return
      @return = Return.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def return_params
      params.require(:return).permit(:date_borrower)
    end
end

app/helpers/returns_helper.rb
module ReturnsHelper
end

app/views/returns/_form.html.erb
<%= form_with(model: return, local: true) do |form| %>
  <% if return.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(return.errors.count, "error") %> prohibited this return from being saved:</h2>

      <ul>
      <% return.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date_borrower %>
    <%= form.date_select :date_borrower %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/returns/edit.html.erb
<h1>Editing Return</h1>

<%= render 'form', return: @return %>

<%= link_to 'Show', @return %> |
<%= link_to 'Back', returns_path %>

app/views/returns/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Returns</h1>

<table>
  <thead>
    <tr>
      <th>Date borrower</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @returns.each do |return| %>
      <tr>
        <td><%= return.date_borrower %></td>
        <td><%= link_to 'Show', return %></td>
        <td><%= link_to 'Edit', edit_return_path(return) %></td>
        <td><%= link_to 'Destroy', return, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Return', new_return_path %>

app/views/returns/new.html.erb
<h1>New Return</h1>

<%= render 'form', return: @return %>

<%= link_to 'Back', returns_path %>

app/views/returns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date borrower:</strong>
  <%= @return.date_borrower %>
</p>

<%= link_to 'Edit', edit_return_path(@return) %> |
<%= link_to 'Back', returns_path %>